name: "Update Version"
author: "Keren Dong"
description: "Update project version"
inputs:
  bump-keyword:
    description: "Increment version(s) by semver keyword"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
