name: "Bump Version"
author: "Keren Dong"
description: "Bump version for Kungfu projects"
inputs:
  token:
    description: "E.g. secrets.GITHUB_TOKEN"
    required: true
  action:
    description: "Choices [auto/prebuild/postbuild/verify]"
    default: "auto"
  no-publish:
    description: "Choices [true/false]"
    default: "false"
  no-protection:
    description: "Choices [true/false]"
    default: "false"
runs:
  using: "node12"
  main: "dist/index.js"
