name: "Bump Version"
author: "Keren Dong"
description: "Bump version for Kungfu projects"
inputs:
  token:
    description: "${{ secrets.GITHUB_TOKEN }}"
    required: true
  head-ref:
    description: "Head git ref of the pull request, e.g. dev/v1/v1.1"
    required: true
  base-ref:
    description: "Base git ref of the pull request, e.g. alpha/v1/v1.1"
    required: true
  keyword:
    description: "choices [auto/verify/patch/premajor/preminor/prerelease]"
    default: "auto"
runs:
  using: "node12"
  main: "dist/index.js"
  post: "dist/index.js"
