name: "Bump Version"
author: "Keren Dong"
description: "Bump version for Kungfu projects"
inputs:
  bump-keyword:
    description: "choices [auto/verify/patch/premajor/preminor/prerelease]"
    default: "true"
  source-ref:
    description: "Source git ref of the pull request, e.g. dev/v1/v1.1"
    required: true
  dest-ref:
    description: "Dest git ref of the pull request, e.g. alpha/v1/v1.1"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
  post: "dist/index.js"
