name: Admin - Bump Version

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type confirm to update version'
        required: true
        default: 'cancel'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kungfu-trader'

      - name: Bump Version
        if: ${{ github.event.inputs.confirm  == 'confirm' }}
        uses: kungfu-trader/action-bump-version@v1
        with:
          bump-keyword: 'preminor'
