name: Bump Version - Prerelease
on:
  pull_request:
    types: [closed]
    branches:
      - alpha/v*/v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          echo pull_request merged [${{ github.event.pull_request.merged }}]

      - name: Bump Version
        uses: kungfu-trader/action-bump-version@v1
        with:
          bump-keyword: "prerelease"
