name: Bump Version - Major

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type confirm to update version'
        required: true
        default: 'cancel'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump Version
        if: ${{ github.event.inputs.confirm  == 'confirm' }}
        uses: kungfu-trader/action-bump-version@v1
        with:
          bump-keyword: 'premajor'
