name: Bump Version - Prerelease
on:
  pull_request:
    types: [closed]
    branches:
      - alpha/v*/v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump Version
        uses: kungfu-trader/action-bump-version@v1
        if: ${{ github.event.pull_request.merged == 'true' }}
        with:
          bump-keyword: "prerelease"
