name: Post Pull Request

on:
  push:
    paths:
      - 'package.json'
      - '**.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kungfu-trader'

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: 'Bump-Action-Artifact-${{github.sha}}'
          path: |
            dist/*
          if-no-files-found: ignore
